jwt:
    secretKey : 413F4428472B4B6250655368566D5970337336763979244226452948404D6351
    expiration : 6000000001234

spring:
  application:
    name: library_management_system
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/library
    username: root
    password: root

server:
  port: 8081